/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quizpoo;

/**
 *
 * @author Alessandro
 */
public class PaginaFinal extends javax.swing.JFrame {

    /**
     * Creates new form PaginaFinal
     */
    public PaginaFinal(int pontos) {
        initComponents();
        Resultado.setText("Você obteve " + pontos + " pontos!");  // Exibe a pontuação
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Resultado = new javax.swing.JLabel();
        NovaTentativa = new javax.swing.JButton();
        Score = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));

        Resultado.setFont(new java.awt.Font("Comic Sans MS", 0, 84)); // NOI18N
        Resultado.setText("Resultado");

        NovaTentativa.setBackground(new java.awt.Color(153, 153, 153));
        NovaTentativa.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        NovaTentativa.setForeground(new java.awt.Color(0, 0, 0));
        NovaTentativa.setText("Nova tentativa");
        NovaTentativa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovaTentativaActionPerformed(evt);
            }
        });

        Score.setBackground(new java.awt.Color(153, 153, 153));
        Score.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        Score.setForeground(new java.awt.Color(0, 0, 0));
        Score.setText("Score");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Resultado)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NovaTentativa, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(Resultado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NovaTentativa, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Score, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NovaTentativaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovaTentativaActionPerformed
        // Redireciona para a tela de quiz novamente
        new Quiz().setVisible(true); // Crie a instância da tela de perguntas (alterar conforme seu fluxo)
        this.dispose(); // Fecha a tela atual
    }//GEN-LAST:event_NovaTentativaActionPerformed

    
    public void exibirResultado(int score) {
        Resultado.setText("Seu Score: " + score);
    }
    
   // Ação que será chamada ao clicar no botão Nova Tentativa
    private void novaTentativaActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // Chama o método para voltar à tela do Quiz
        voltarParaQuiz();
    }                                             

    // Método para voltar à tela do Quiz
    private void voltarParaQuiz() {
        Quiz quizTela = new Quiz();  // Cria a instância da tela Quiz (não Questoes)
        quizTela.setVisible(true);  // Torna a tela Quiz visível
        this.setVisible(false);  // Fecha a tela da Página Final
        this.dispose();  // Libera os recursos da tela atual
    }

    /**
     * @param args the command line arguments
     */


    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NovaTentativa;
    private javax.swing.JLabel Resultado;
    private javax.swing.JButton Score;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
