/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quizpoo;

import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Alessandro
 */
public class Quiz extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Quiz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PainelVerde = new javax.swing.JPanel();
        PainelQuiz = new javax.swing.JPanel();
        Titulo = new javax.swing.JPanel();
        TituloAcesso = new javax.swing.JLabel();
        Nome = new javax.swing.JLabel();
        RA = new javax.swing.JLabel();
        CampoRA = new javax.swing.JTextField();
        CampoNome = new javax.swing.JTextField();
        BotaoAcesso = new javax.swing.JButton();
        ImagemUsuario = new javax.swing.JLabel();
        ImagemRA = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/guana6.png"))); // NOI18N

        PainelVerde.setBackground(new java.awt.Color(153, 153, 153));
        PainelVerde.setForeground(new java.awt.Color(255, 255, 255));

        PainelQuiz.setBackground(new java.awt.Color(153, 255, 153));
        PainelQuiz.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Titulo.setBackground(new java.awt.Color(0, 153, 0));
        Titulo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        TituloAcesso.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        TituloAcesso.setForeground(new java.awt.Color(255, 255, 255));
        TituloAcesso.setText("Acesso ao Quiz");

        javax.swing.GroupLayout TituloLayout = new javax.swing.GroupLayout(Titulo);
        Titulo.setLayout(TituloLayout);
        TituloLayout.setHorizontalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(TituloAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        TituloLayout.setVerticalGroup(
            TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TituloLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(TituloAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Nome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Nome.setForeground(new java.awt.Color(0, 0, 0));
        Nome.setText("RA      ");

        RA.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        RA.setForeground(new java.awt.Color(0, 0, 0));
        RA.setText("Nome");

        CampoRA.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        CampoRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampoRAActionPerformed(evt);
            }
        });

        CampoNome.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        BotaoAcesso.setBackground(new java.awt.Color(153, 153, 153));
        BotaoAcesso.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        BotaoAcesso.setForeground(new java.awt.Color(0, 0, 0));
        BotaoAcesso.setText("Entrar");
        BotaoAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAcessoActionPerformed(evt);
            }
        });

        ImagemUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/do-utilizador.png"))); // NOI18N

        ImagemRA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cracha.png"))); // NOI18N

        javax.swing.GroupLayout PainelQuizLayout = new javax.swing.GroupLayout(PainelQuiz);
        PainelQuiz.setLayout(PainelQuizLayout);
        PainelQuizLayout.setHorizontalGroup(
            PainelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQuizLayout.createSequentialGroup()
                .addGroup(PainelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PainelQuizLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PainelQuizLayout.createSequentialGroup()
                        .addGroup(PainelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PainelQuizLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(ImagemUsuario))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelQuizLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ImagemRA)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PainelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoRA)
                            .addComponent(CampoNome)
                            .addGroup(PainelQuizLayout.createSequentialGroup()
                                .addGroup(PainelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RA))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(37, 37, 37)))
                .addGap(18, 18, 18))
        );
        PainelQuizLayout.setVerticalGroup(
            PainelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelQuizLayout.createSequentialGroup()
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(RA, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PainelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelQuizLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoNome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelQuizLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ImagemUsuario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelQuizLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CampoRA, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelQuizLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(ImagemRA)))
                .addGap(29, 29, 29)
                .addComponent(BotaoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelVerdeLayout = new javax.swing.GroupLayout(PainelVerde);
        PainelVerde.setLayout(PainelVerdeLayout);
        PainelVerdeLayout.setHorizontalGroup(
            PainelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVerdeLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(PainelQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PainelVerdeLayout.setVerticalGroup(
            PainelVerdeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelVerdeLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(PainelQuiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PainelVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CampoRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoRAActionPerformed
    // Obter os valores do JTextField
    String nome = CampoNome.getText();
    String raText = CampoRA.getText();

    // Validar se os campos não estão vazios
    if (nome.isEmpty() || raText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, insira tanto o Nome quanto o RA.");
        return;
    }

    // Tentar converter o RA para inteiro
    int ra;
    try {
        ra = Integer.parseInt(raText);  // Converte o RA para inteiro
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "O RA deve ser um número válido.");
        return; // Sai do método se o RA não for válido
    }

    // Conectar ao banco de dados e inserir o usuário se não existir
    try (Connection conn = Main.conexaoBanco()) {
        // Verificar se o usuário já existe
        String sql = "SELECT * FROM Usuario WHERE RA = ? AND nome = ?";
        try (PreparedStatement stmt = conn.prepareStatement(sql)) {
            stmt.setInt(1, ra);
            stmt.setString(2, nome);
            ResultSet rs = stmt.executeQuery();

            if (!rs.next()) {
                // Inserir novo usuário caso não exista
                String insertSql = "INSERT INTO Usuario (nome, RA) VALUES (?, ?)";
                try (PreparedStatement insertStmt = conn.prepareStatement(insertSql)) {
                    insertStmt.setString(1, nome);
                    insertStmt.setInt(2, ra);
                    insertStmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Usuário registrado com sucesso!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuário já registrado!");
            }
        }

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Erro ao acessar o banco de dados: " + e.getMessage());
    }

    }//GEN-LAST:event_CampoRAActionPerformed

    private void BotaoAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAcessoActionPerformed
        String ra = CampoRA.getText();
        String nome = CampoNome.getText();
        System.out.println(ra + nome);
            if (!ra.equals("") || !nome.equals("")) {
                // Cria um objeto Usuario
                //Usuario usuario = new Usuario(id, ra, nome);
                // Abre a próxima tela de questões
                Questoes telaQuestoes = new Questoes();
                telaQuestoes.setVisible(true);
                dispose();  // Fecha a tela atual
    }//GEN-LAST:event_BotaoAcessoActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAcesso;
    private javax.swing.JTextField CampoNome;
    private javax.swing.JTextField CampoRA;
    private javax.swing.JLabel ImagemRA;
    private javax.swing.JLabel ImagemUsuario;
    private javax.swing.JLabel Nome;
    private javax.swing.JPanel PainelQuiz;
    private javax.swing.JPanel PainelVerde;
    private javax.swing.JLabel RA;
    private javax.swing.JPanel Titulo;
    private javax.swing.JLabel TituloAcesso;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
